### ISSUE TITLE
Not working [ws_connect()]

### ISSUE THREAD

**Issue by VaporrPlays** [Exaphis/HackQ-Trivia#106]
I get this error.

>  ===
getting

Show active, connecting to socket at https://ws-quiz.hype.space/ws/44865
Traceback (most recent call last):
  File "C:\Users\VaporrPlays\Downloads\HackQ-Trivia-master\hq_main.py", line 51, in <module>
    asyncio.get_event_loop().run_until_complete(networking.websocket_handler(socket, headers))
  File "C:\Users\VaporrPlays\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "C:\Users\VaporrPlays\Downloads\HackQ-Trivia-master\networking.py", line 46, in websocket_handler
    async with session.ws_connect(uri, headers=headers, heartbeat=5, timeout=30) as ws:
TypeError: ws_connect() got an unexpected keyword argument 'heartbeat'
>>>

**Comment by Exaphis** [comment]
Try cloning the repo again and installing the requirements.
