### ISSUE TITLE
SyntaxError: invalid syntax  PLEASE HELP.

### ISSUE THREAD

**Issue by kazzandu** [Exaphis/HackQ-Trivia#152]
First time getting this set up and this is what happened. Any tips please?

Or could someone help me set it up? I appreciate it a lot. Thanks!

\HackQ-Trivia>python hq_main.py
Traceback (most recent call last):
  File "hq_main.py", line 9, in <module>
    import networking
  File "C:\Users\Kazza\HackQ-Trivia\networking.py", line 6, in <module>
    import aiohttp
  File "D:\Python\lib\site-packages\aiohttp\__init__.py", line 10, in <module>
    from .protocol import *  # noqa
  File "D:\Python\lib\site-packages\aiohttp\protocol.py", line 18, in <module>
    from .helpers import reify
  File "D:\Python\lib\site-packages\aiohttp\helpers.py", line 25
    ensure_future = asyncio.async
                                ^
SyntaxError: invalid syntax

**Comment by kazzandu** [comment]
FIXED. Didnt install properly. Reinstalled and now it works.

**Comment by kazzandu** [comment]
Tried reinstalling it and still got the same issue. please help.

**Comment by Exaphis** [comment]
Are you using Python 3.5+?

**Comment by kazzandu** [comment]
yes

**Comment by Exaphis** [comment]
Are you using the latest version of aiohttp?
