### ISSUE TITLE
time out error

### ISSUE THREAD

**Issue by ks4ghz** [Exaphis/HackQ-Trivia#154]
Running method 1
{'charlie chaplin': 0, 'gary cooper': 0, 'humphrey boga': 0}
Running method 2
{'Charlie Chaplin': {'charlie': 0, 'chaplin': 0}, 'Gary Cooper': {'gary': 0, 'cooper': 0}, 'Humphrey Boga': {'humphrey': 0, 'boga': 0}}
[('The', 'DT'), ('18th-century', 'JJ'), ('Russian', 'JJ'), ('Enlightenment', 'NN'), ('featured', 'VBD'), ('a', 'DT'), ('friendship', 'NN'), ('between', 'IN'), ('the', 'DT'), ('Russian', 'NNP'), ('empress', 'NN'), ('and', 'CC'), ('what', 'WP'), ('writer', 'NN'), ('?', '.')]
Question nouns: {'russian enlightenment', 'enlightenment'}
Running method 3
Search processed
Server timeout/error to https://www.imdb.com/name/nm0000011/bio
ERROR:root:Server timeout/error to https://www.imdb.com/name/nm0000011/bio
Traceback (most recent call last):
  File "/home/ks4ghz/Downloads/HackQ-Trivia-master (5)/networking.py", line 17, in fetch
    return await response.text()
  File "/home/ks4ghz/.local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 906, in text
    await self.read()
  File "/home/ks4ghz/.local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 871, in read
    self._body = await self.content.read()
  File "/home/ks4ghz/.local/lib/python3.6/site-packages/aiohttp/streams.py", line 312, in read
    block = await self.readany()
  File "/home/ks4ghz/.local/lib/python3.6/site-packages/aiohttp/streams.py", line 328, in readany
    await self._wait('readany')
  File "/home/ks4ghz/.local/lib/python3.6/site-packages/aiohttp/streams.py", line 250, in _wait
    await waiter
  File "/home/ks4ghz/.local/lib/python3.6/site-packages/aiohttp/helpers.py", line 677, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
Server timeout/error to https://www.imdb.com/name/nm0000011/
ERROR:root:Server timeout/error to https://www.imdb.com/name/nm0000011/
Traceback (most recent call last):
  File "/home/ks4ghz/Downloads/HackQ-Trivia-master (5)/networking.py", line 17, in fetch
    return await response.text()
  File "/home/ks4ghz/.local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 906, in text
    await self.read()
  File "/home/ks4ghz/.local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 871, in read
    self._body = await self.content.read()
  File "/home/ks4ghz/.local/lib/python3.6/site-packages/aiohttp/streams.py", line 312, in read
    block = await self.readany()
  File "/home/ks4ghz/.local/lib/python3.6/site-packages/aiohttp/streams.py", line 328, in readany
    await self._wait('readany')
  File "/home/ks4ghz/.local/lib/python3.6/site-packages/aiohttp/streams.py", line 250, in _wait
    await waiter
  File "/home/ks4ghz/.local/lib/python3.6/site-packages/aiohttp/helpers.py", line 677, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
URLs fetched

**Comment by Exaphis** [comment]
Let me know if this still happens in the updated version.
