### ISSUE TITLE
bearer finder TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by KianBrose** [Exaphis/HackQ-Trivia#183]
Hello there! I just finished setting up everything as the README file said, entered the google search API token and GoogleCseId, but when I try to run 
python hackq_trivia/bearer_finder.py
(Note: I am using python 3.7.0 64 bit)
I get the following error

![tt](https://user-images.githubusercontent.com/62078964/87358221-a511d700-c565-11ea-9fb4-1dd65744c05b.png)

![temp](https://user-images.githubusercontent.com/62078964/87358167-8a3f6280-c565-11ea-9adc-8fb02cb3bf02.png)

did I miss anything?

**Comment by Exaphis** [comment]
Interesting. I've added logging to bearer_finder.py. Get the new version and report back with your `data.log` file. Make sure to follow the new bearer_finder instructions in the README.

**Comment by KianBrose** [comment]
Hello!
I downloaded the latest Master commit and tried running 
`python hackq_trivia.bearer_finder`
output:
`(null): can't open file 'hackq_trivia.bearer_finder': [Errno 2] No such file or directory  `

I changed the command to this:
`python hackq_trivia/bearer_finder.py` (Since this points to the bearer finder file)
The code did not output a data.log file but gave this error instead

C:\Users\Kian\Desktop\HackQ-Trivia-master (1)\HackQ-Trivia-master>python hackq_trivia/bearer_finder.py                                                                                                                                       
Traceback (most recent call last):                                                                                                                                                                                                             File "hackq_trivia/bearer_finder.py", line 6, in <module>                                                                                                                                                                                      from hackq_trivia.hq_main import init_root_logger                                                                                                                                                                                        ModuleNotFoundError: No module named 'hackq_trivia' 

Running `python hackq_trivia/bearer_finder.py` with -m gives this output:
`C:\Users\Kian\AppData\Local\Programs\Python\Python37\python.exe: Error while finding module specification for 'hackq_trivia/bearer_finder.py' (ModuleNotFoundError: No module named 'hackq_trivia/bearer_finder') `

**Comment by Exaphis** [comment]
Should be `python -m hackq_trivia.bearer_finder`, not `python hackq_trivia.bearer_finder`.

**Comment by KianBrose** [comment]
Output of `python -m hackq_trivia.bearer_finder`

Traceback (most recent call last):                                                                                                                                                                                                             File "C:\Users\Kian\AppData\Local\Programs\Python\Python37\lib\site-packages\nltk\corpus\util.py", line 83, in __load                                                                                                                          root = nltk.data.find("{}/{}".format(self.subdir, zip_name))                                                                                                                                                                               File "C:\Users\Kian\AppData\Local\Programs\Python\Python37\lib\site-packages\nltk\data.py", line 585, in find                                                                                                                                  raise LookupError(resource_not_found)                                                                                                                                                                                                    LookupError:                                                                                                                                                                                                                                 **********************************************************************                                                                                                                                                                         Resource [93mstopwords[0m not found.                                                                                                                                                                                                       Please use the NLTK Downloader to obtain the resource:                                                                                                                                                                                                                                                                                                                                                                                                                                    [31m>>> import nltk                                                                                                                                                                                                                         >>> nltk.download('stopwords')                                                                                                                                                                                                               [0m                                                                                                                                                                                                                                         For more information see: https://www.nltk.org/data.html                                                                                                                                                                                                                                                                                                                                                                                                                                  Attempted to load [93mcorpora/stopwords.zip/stopwords/[0m                                                                                                                                                                                                                                                                                                                                                                                                                               Searched in:                                                                                                                                                                                                                                   - 'C:\\Users\\Kian/nltk_data'                                                                                                                                                                                                                - 'C:\\Users\\Kian\\AppData\\Local\\Programs\\Python\\Python37\\nltk_data'                                                                                                                                                                   - 'C:\\Users\\Kian\\AppData\\Local\\Programs\\Python\\Python37\\share\\nltk_data'                                                                                                                                                            - 'C:\\Users\\Kian\\AppData\\Local\\Programs\\Python\\Python37\\lib\\nltk_data'                                                                                                                                                              - 'C:\\Users\\Kian\\AppData\\Roaming\\nltk_data'                                                                                                                                                                                             - 'C:\\nltk_data'                                                                                                                                                                                                                            - 'D:\\nltk_data'                                                                                                                                                                                                                            - 'E:\\nltk_data'                                                                                                                                                                                                                        **********************************************************************                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                                                                                                                                                                                       Traceback (most recent call last):                                                                                                                                                                                                             File "C:\Users\Kian\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main                                                                                                                                     "__main__", mod_spec)                                                                                                                                                                                                                      File "C:\Users\Kian\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code                                                                                                                                                exec(code, run_globals)                                                                                                                                                                                                                    File "C:\Users\Kian\Desktop\HackQ-Trivia-master (1)\HackQ-Trivia-master\hackq_trivia\bearer_finder.py", line 6, in <module>                                                                                                                    from hackq_trivia.hq_main import init_root_logger                                                                                                                                                                                          File "C:\Users\Kian\Desktop\HackQ-Trivia-master (1)\HackQ-Trivia-master\hackq_trivia\hq_main.py", line 14, in <module>                                                                                                                         from hackq_trivia.live_show import LiveShow                                                                                                                                                                                                File "C:\Users\Kian\Desktop\HackQ-Trivia-master (1)\HackQ-Trivia-master\hackq_trivia\live_show.py", line 9, in <module>                                                                                                                        from hackq_trivia.question_handler import QuestionHandler                                                                                                                                                                                  File "C:\Users\Kian\Desktop\HackQ-Trivia-master (1)\HackQ-Trivia-master\hackq_trivia\question_handler.py", line 14, in <module>                                                                                                                class QuestionHandler:                                                                                                                                                                                                                     File "C:\Users\Kian\Desktop\HackQ-Trivia-master (1)\HackQ-Trivia-master\hackq_trivia\question_handler.py", line 15, in QuestionHandler                                                                                                         STOPWORDS = set(nltk.corpus.stopwords.words('english')) - {'most', 'least'}                                                                                                                                                                File "C:\Users\Kian\AppData\Local\Programs\Python\Python37\lib\site-packages\nltk\corpus\util.py", line 120, in __getattr__                                                                                                                    self.__load()                                                                                                                                                                                                                              File "C:\Users\Kian\AppData\Local\Programs\Python\Python37\lib\site-packages\nltk\corpus\util.py", line 85, in __load                                                                                                                          raise e                                                                                                                                                                                                                                    File "C:\Users\Kian\AppData\Local\Programs\Python\Python37\lib\site-packages\nltk\corpus\util.py", line 80, in __load                                                                                                                          root = nltk.data.find("{}/{}".format(self.subdir, self.__name))                                                                                                                                                                            File "C:\Users\Kian\AppData\Local\Programs\Python\Python37\lib\site-packages\nltk\data.py", line 585, in find                                                                                                                                  raise LookupError(resource_not_found)                                                                                                                                                                                                    LookupError:                                                                                                                                                                                                                                 **********************************************************************                                                                                                                                                                         Resource [93mstopwords[0m not found.                                                                                                                                                                                                       Please use the NLTK Downloader to obtain the resource:                                                                                                                                                                                                                                                                                                                                                                                                                                    [31m>>> import nltk                                                                                                                                                                                                                         >>> nltk.download('stopwords')                                                                                                                                                                                                               [0m                                                                                                                                                                                                                                         For more information see: https://www.nltk.org/data.html                                                                                                                                                                                                                                                                                                                                                                                                                                  Attempted to load [93mcorpora/stopwords[0m                                                                                                                                                                                                                                                                                                                                                                                                                                              Searched in:                                                                                                                                                                                                                                   - 'C:\\Users\\Kian/nltk_data'                                                                                                                                                                                                                - 'C:\\Users\\Kian\\AppData\\Local\\Programs\\Python\\Python37\\nltk_data'                                                                                                                                                                   - 'C:\\Users\\Kian\\AppData\\Local\\Programs\\Python\\Python37\\share\\nltk_data'                                                                                                                                                            - 'C:\\Users\\Kian\\AppData\\Local\\Programs\\Python\\Python37\\lib\\nltk_data'                                                                                                                                                              - 'C:\\Users\\Kian\\AppData\\Roaming\\nltk_data'                                                                                                                                                                                             - 'C:\\nltk_data'                                                                                                                                                                                                                            - 'D:\\nltk_data'                                                                                                                                                                                                                            - 'E:\\nltk_data'                                                                                                                                                                                                                        **********************************************************************

**Comment by Exaphis** [comment]
Fixed, pull the repo and try again. Alternatively follow the steps in the error message to download the resource.

**Comment by KianBrose** [comment]
Ran the command on the new version

Here is the output:
Your bearer token is:                                                                                                   Traceback (most recent call last):                                                                                        File "C:\Users\Kian\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main                "__main__", mod_spec)                                                                                                 File "C:\Users\Kian\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code                           exec(code, run_globals)                                                                                               File "C:\Users\Kian\Desktop\HackQ-Trivia-master (2)\HackQ-Trivia-master\hackq_trivia\bearer_finder.py", line 65, in <module>                                                                                                                      main()                                                                                                                File "C:\Users\Kian\Desktop\HackQ-Trivia-master (2)\HackQ-Trivia-master\hackq_trivia\bearer_finder.py", line 59, in main                                                                                                                          print(auth_resp['auth']['authToken'])                                                                               TypeError: 'NoneType' object is not subscriptable    

Here is the log file
[data.log](https://github.com/Exaphis/HackQ-Trivia/files/4925799/data.log)

I removed my phone number for privacy reasons, though I would comment my phone begins with +46 (swedish extension)

**Comment by Exaphis** [comment]
Hmmm, can't seem to reproduce. You have logged into HQ Trivia with the account registered to this phone number, right?

**Comment by KianBrose** [comment]
Yes, I tried uninstalling and reinstalling python 3.7 and it seems to work properly now
