### ISSUE TITLE
Logging error

### ISSUE THREAD

**Issue by pk372** [Exaphis/HackQ-Trivia#190]
All working fine. but irritated with some garbage output. i tried to figure out error but couldn't able to do it

What crunchy topping is typically put on a Caesar salad?
Choices: Chickpeas, Tortilla chips, Croutons
Searching...
Question keywords: ['crunchy', 'topping', 'typically', 'put', 'Caesar', 'salad']
Running method 1
{'Chickpeas': 2, 'Tortilla chips': 0, 'Croutons': 44}
Croutons
Running method 2
{'Chickpeas': 2, 'Tortilla chips': 2, 'Croutons': 44}
Croutons
Search took 6.36 seconds
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\ipiyu\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\ipiyu\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 190-195: character maps to <undefined>
Call stack:
  File "C:\Users\ipiyu\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ipiyu\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ipiyu\Desktop\HackQ-Trivia-master\HackQ-Trivia-master\hackq_trivia\hq_main.py", line 172, in <module>
    HackQ().connect()
  File "C:\Users\ipiyu\Desktop\HackQ-Trivia-master\HackQ-Trivia-master\hackq_trivia\hq_main.py", line 121, in connect
    asyncio.run(self.__connect_show(websocket_uri))
  File "C:\Users\ipiyu\AppData\Local\Programs\Python\Python38\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\ipiyu\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "C:\Users\ipiyu\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\ipiyu\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Users\ipiyu\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "C:\Users\ipiyu\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ipiyu\Desktop\HackQ-Trivia-master\HackQ-Trivia-master\hackq_trivia\hq_main.py", line 112, in __connect_show
    await show.connect(uri)
  File "C:\Users\ipiyu\Desktop\HackQ-Trivia-master\HackQ-Trivia-master\hackq_trivia\live_show.py", line 36, in connect
    self.logger.debug(message)
Message: {'type': 'interaction', 'ts': '2020-07-28T01:07:58.555Z', 'itemId': 'chat', 'userId': 24284577, 'metadata': {'username': 'SnoDragon', 'message': '👁 👄👃🏾👄👁', 'messageId': '3016C9A3-3F44-40D0-A123-8EEBD625BB92  ', 'userId': 24284577, 'interaction': 'chat', 'avatarUrl': 'https://cdn.prod.hype.space/72x72/a/24284577-AoN1SG'}, 'sent': '2020-07-28T01:07:58.754Z', 'c': 11}
Arguments: ()

**Comment by Exaphis** [comment]
Yeah, this has been a longstanding bug. You can comment out https://github.com/Exaphis/HackQ-Trivia/blob/master/hackq_trivia/live_show.py#L36 or wrap it in a try/except if you want.

**Comment by pk372** [comment]
> Yeah, this has been a longstanding bug. You can comment out https://github.com/Exaphis/HackQ-Trivia/blob/master/hackq_trivia/live_show.py#L36 or wrap it in a try/except if you want.

Thanks
